# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@actions/expressions-0.3.15" = {
      name = "_at_actions_slash_expressions";
      packageName = "@actions/expressions";
      version = "0.3.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/expressions/-/expressions-0.3.15.tgz";
        sha512 = "OuYp1jaCNyS+jBYnD5w9ycqsYJnKamczP0PCMbrjSo/CMkM2GAnZbFxBh3Uij97tA5xrcapIr8TE/1CQk3oLug==";
      };
    };
    "@actions/languageserver-0.3.15" = {
      name = "_at_actions_slash_languageserver";
      packageName = "@actions/languageserver";
      version = "0.3.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageserver/-/languageserver-0.3.15.tgz";
        sha512 = "JpP6H83fY1FxXlr+NZ0EJW0PEGk6TSkliJ6/LpZ4IBtOIps3dcrBQTAOLrTEaRoXmi84q7qabSaK0KIb+lHfdA==";
      };
    };
    "@actions/languageservice-0.3.15" = {
      name = "_at_actions_slash_languageservice";
      packageName = "@actions/languageservice";
      version = "0.3.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/languageservice/-/languageservice-0.3.15.tgz";
        sha512 = "xiN81ovC6HDXun8u+FD0RE5inWWVCeBsAdfzQ+fyTCxzMLZR5NKeF9b3vqpdXIuPApb3sWQtjY/BGFmLzyCcHA==";
      };
    };
    "@actions/workflow-parser-0.3.15" = {
      name = "_at_actions_slash_workflow-parser";
      packageName = "@actions/workflow-parser";
      version = "0.3.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/@actions/workflow-parser/-/workflow-parser-0.3.15.tgz";
        sha512 = "AaBiJ/urwk/0mfkwqbNHVsDh9cduhpWaj9c1zhxFI0QHt1RlSX5ANihtZZEfHu5GXIpsciYnI7nMN4loBDAp7g==";
      };
    };
    "@octokit/auth-token-3.0.4" = {
      name = "_at_octokit_slash_auth-token";
      packageName = "@octokit/auth-token";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/auth-token/-/auth-token-3.0.4.tgz";
        sha512 = "TWFX7cZF2LXoCvdmJWY7XVPi74aSY0+FfBZNSXEXFkMpjcqsQwDSYVv5FhRFaI0V1ECnwbz4j59T/G+rXNWaIQ==";
      };
    };
    "@octokit/core-4.2.4" = {
      name = "_at_octokit_slash_core";
      packageName = "@octokit/core";
      version = "4.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/core/-/core-4.2.4.tgz";
        sha512 = "rYKilwgzQ7/imScn3M9/pFfUf4I1AZEH3KhyJmtPdE2zfaXAn2mFfUy4FbKewzc2We5y/LlKLj36fWJLKC2SIQ==";
      };
    };
    "@octokit/endpoint-7.0.6" = {
      name = "_at_octokit_slash_endpoint";
      packageName = "@octokit/endpoint";
      version = "7.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/endpoint/-/endpoint-7.0.6.tgz";
        sha512 = "5L4fseVRUsDFGR00tMWD/Trdeeihn999rTMGRMC1G/Ldi1uWlWJzI98H4Iak5DB/RVvQuyMYKqSK/R6mbSOQyg==";
      };
    };
    "@octokit/graphql-5.0.6" = {
      name = "_at_octokit_slash_graphql";
      packageName = "@octokit/graphql";
      version = "5.0.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/graphql/-/graphql-5.0.6.tgz";
        sha512 = "Fxyxdy/JH0MnIB5h+UQ3yCoh1FG4kWXfFKkpWqjZHw/p+Kc8Y44Hu/kCgNBT6nU1shNumEchmW/sUO1JuQnPcw==";
      };
    };
    "@octokit/openapi-types-18.1.1" = {
      name = "_at_octokit_slash_openapi-types";
      packageName = "@octokit/openapi-types";
      version = "18.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/openapi-types/-/openapi-types-18.1.1.tgz";
        sha512 = "VRaeH8nCDtF5aXWnjPuEMIYf1itK/s3JYyJcWFJT8X9pSNnBtriDf7wlEWsGuhPLl4QIH4xM8fqTXDwJ3Mu6sw==";
      };
    };
    "@octokit/plugin-paginate-rest-6.1.2" = {
      name = "_at_octokit_slash_plugin-paginate-rest";
      packageName = "@octokit/plugin-paginate-rest";
      version = "6.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-6.1.2.tgz";
        sha512 = "qhrmtQeHU/IivxucOV1bbI/xZyC/iOBhclokv7Sut5vnejAIAEXVcGQeRpQlU39E0WwK9lNvJHphHri/DB6lbQ==";
      };
    };
    "@octokit/plugin-request-log-1.0.4" = {
      name = "_at_octokit_slash_plugin-request-log";
      packageName = "@octokit/plugin-request-log";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-request-log/-/plugin-request-log-1.0.4.tgz";
        sha512 = "mLUsMkgP7K/cnFEw07kWqXGF5LKrOkD+lhCrKvPHXWDywAwuDUeDwWBpc69XK3pNX0uKiVt8g5z96PJ6z9xCFA==";
      };
    };
    "@octokit/plugin-rest-endpoint-methods-7.2.3" = {
      name = "_at_octokit_slash_plugin-rest-endpoint-methods";
      packageName = "@octokit/plugin-rest-endpoint-methods";
      version = "7.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/plugin-rest-endpoint-methods/-/plugin-rest-endpoint-methods-7.2.3.tgz";
        sha512 = "I5Gml6kTAkzVlN7KCtjOM+Ruwe/rQppp0QU372K1GP7kNOYEKe8Xn5BW4sE62JAHdwpq95OQK/qGNyKQMUzVgA==";
      };
    };
    "@octokit/request-6.2.8" = {
      name = "_at_octokit_slash_request";
      packageName = "@octokit/request";
      version = "6.2.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request/-/request-6.2.8.tgz";
        sha512 = "ow4+pkVQ+6XVVsekSYBzJC0VTVvh/FCTUUgTsboGq+DTeWdyIFV8WSCdo0RIxk6wSkBTHqIK1mYuY7nOBXOchw==";
      };
    };
    "@octokit/request-error-3.0.3" = {
      name = "_at_octokit_slash_request-error";
      packageName = "@octokit/request-error";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/request-error/-/request-error-3.0.3.tgz";
        sha512 = "crqw3V5Iy2uOU5Np+8M/YexTlT8zxCfI+qu+LxUB7SZpje4Qmx3mub5DfEKSO8Ylyk0aogi6TYdf6kxzh2BguQ==";
      };
    };
    "@octokit/rest-19.0.13" = {
      name = "_at_octokit_slash_rest";
      packageName = "@octokit/rest";
      version = "19.0.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/rest/-/rest-19.0.13.tgz";
        sha512 = "/EzVox5V9gYGdbAI+ovYj3nXQT1TtTHRT+0eZPcuC05UFSWO3mdO9UY1C0i2eLF9Un1ONJkAk+IEtYGAC+TahA==";
      };
    };
    "@octokit/tsconfig-1.0.2" = {
      name = "_at_octokit_slash_tsconfig";
      packageName = "@octokit/tsconfig";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/tsconfig/-/tsconfig-1.0.2.tgz";
        sha512 = "I0vDR0rdtP8p2lGMzvsJzbhdOWy405HcGovrspJ8RRibHnyRgggUSNO5AIox5LmqiwmatHKYsvj6VGFHkqS7lA==";
      };
    };
    "@octokit/types-10.0.0" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "10.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-10.0.0.tgz";
        sha512 = "Vm8IddVmhCgU1fxC1eyinpwqzXPEYu0NrYzD3YZjlGjyftdLBTeqNblRC0jmJmgxbJIsQlyogVeGnrNaaMVzIg==";
      };
    };
    "@octokit/types-9.3.2" = {
      name = "_at_octokit_slash_types";
      packageName = "@octokit/types";
      version = "9.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@octokit/types/-/types-9.3.2.tgz";
        sha512 = "D4iHGTdAnEEVsB8fl95m1hiz7D5YiRdQ9b/OEb3BYRVwbLsGHcRVPz+u+BgRLNk0Q0/4iZCBqDN96j2XNxfXrA==";
      };
    };
    "before-after-hook-2.2.3" = {
      name = "before-after-hook";
      packageName = "before-after-hook";
      version = "2.2.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/before-after-hook/-/before-after-hook-2.2.3.tgz";
        sha512 = "NzUnlZexiaH/46WDhANlyR2bXRopNg4F/zuSA3OpZnllCUgRaOF2znDioDWrmbNVsuZk6l9pMquQB38cfBZwkQ==";
      };
    };
    "cronstrue-2.57.0" = {
      name = "cronstrue";
      packageName = "cronstrue";
      version = "2.57.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/cronstrue/-/cronstrue-2.57.0.tgz";
        sha512 = "gQOfxJa1RA9uDT4hx37NshhX4dW9t9zTCtIYu15LUziH+mkpuLXYcSEyM8ZewMJ2p8UVuHGjI3n4hGpu3HtCbg==";
      };
    };
    "deprecation-2.3.1" = {
      name = "deprecation";
      packageName = "deprecation";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/deprecation/-/deprecation-2.3.1.tgz";
        sha512 = "xmHIy4F3scKVwMsQ4WnVaS8bHOx0DmVwRywosKhaILI0ywMDWPtBSku2HNxRvF7jtwDRsoEwYQSfbxj8b7RlJQ==";
      };
    };
    "encoding-0.1.13" = {
      name = "encoding";
      packageName = "encoding";
      version = "0.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/encoding/-/encoding-0.1.13.tgz";
        sha512 = "ETBauow1T35Y/WZMkio9jiM0Z5xjHHmJ4XmjZOq1l/dXz3lr2sRn87nJy20RupqSh1F2m3HHPSp8ShIPQJrJ3A==";
      };
    };
    "iconv-lite-0.6.3" = {
      name = "iconv-lite";
      packageName = "iconv-lite";
      version = "0.6.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/iconv-lite/-/iconv-lite-0.6.3.tgz";
        sha512 = "4fCk79wshMdzMp2rH06qWrJE4iolqLhCUH+OiuIgU++RB0+94NlDL81atO7GX55uUKueo0txHNtvEyI6D7WdMw==";
      };
    };
    "is-plain-object-5.0.0" = {
      name = "is-plain-object";
      packageName = "is-plain-object";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-object/-/is-plain-object-5.0.0.tgz";
        sha512 = "VRSzKkbMm5jMDoKLbltAkFQ5Qr7VDiTFGXxYFXXowVj387GeGNOCsOH6Msy00SGZ3Fp84b1Naa1psqgcCIEP5Q==";
      };
    };
    "node-fetch-2.7.0" = {
      name = "node-fetch";
      packageName = "node-fetch";
      version = "2.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-fetch/-/node-fetch-2.7.0.tgz";
        sha512 = "c4FRfUm/dbcWZ7U+1Wq0AwCyFL+3nt2bEw05wfxSz+DWpWsitgmSgYmy2dQdWyKC1694ELPqMs/YzUSNozLt8A==";
      };
    };
    "once-1.4.0" = {
      name = "once";
      packageName = "once";
      version = "1.4.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/once/-/once-1.4.0.tgz";
        sha512 = "lNaJgI+2Q5URQBkccEKHTQOPaXdUxnZZElQTZY0MFUAuaEqe1E+Nyvgdz/aIyNi6Z9MzO5dv1H8n58/GELp3+w==";
      };
    };
    "safer-buffer-2.1.2" = {
      name = "safer-buffer";
      packageName = "safer-buffer";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/safer-buffer/-/safer-buffer-2.1.2.tgz";
        sha512 = "YZo3K82SD7Riyi0E1EQPojLz7kpepnSQI9IyPbHHg1XXXevb5dJI7tpyN2ADxGcQbHG7vcyRHk0cbwqcQriUtg==";
      };
    };
    "tr46-0.0.3" = {
      name = "tr46";
      packageName = "tr46";
      version = "0.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tr46/-/tr46-0.0.3.tgz";
        sha512 = "N3WMsuqV66lT30CrXNbEjx4GEwlow3v6rr4mCcv6prnfwhS01rkgyFdjPNBYd9br7LpXV1+Emh01fHnq2Gdgrw==";
      };
    };
    "typescript-5.8.2" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.8.2.tgz";
        sha512 = "aJn6wq13/afZp/jT9QZmwEjDqqvSGp1VT5GVg+f/t6/oVyrgXM6BY1h9BRh/O5p3PlUPAe+WuiEZOmb/49RqoQ==";
      };
    };
    "universal-user-agent-6.0.1" = {
      name = "universal-user-agent";
      packageName = "universal-user-agent";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/universal-user-agent/-/universal-user-agent-6.0.1.tgz";
        sha512 = "yCzhz6FN2wU1NiiQRogkTQszlQSlpWaw8SvVegAc+bDxbzHgh1vX8uIe8OYyMH6DwH+sdTJsgMl36+mSMdRJIQ==";
      };
    };
    "vscode-jsonrpc-8.1.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.1.0.tgz";
        sha512 = "6TDy/abTQk+zDGYazgbIPc+4JoXdwC8NHU9Pbn4UJP1fehUyZmM4RHp5IthX7A6L5KS30PRui+j+tbbMMMafdw==";
      };
    };
    "vscode-languageserver-8.1.0" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "8.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-8.1.0.tgz";
        sha512 = "eUt8f1z2N2IEUDBsKaNapkz7jl5QpskN2Y0G01T/ItMxBxw1fJwvtySGB9QMecatne8jFIWJGWI61dWjyTLQsw==";
      };
    };
    "vscode-languageserver-protocol-3.17.3" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.3.tgz";
        sha512 = "924/h0AqsMtA5yK22GgMtCYiMdCOtWTSGgUOkgEDX+wk2b0x4sAfLiO4NxBxqbiVtz7K7/1/RgVrVI0NClZwqA==";
      };
    };
    "vscode-languageserver-textdocument-1.0.12" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz";
        sha512 = "cxWNPesCnQCcMPeenjKKsOCKQZ/L6Tv19DTRIGuLWe32lyzWhihGVJ/rcckZXJxfdKCFvRLS3fpBIsV/ZGX4zA==";
      };
    };
    "vscode-languageserver-types-3.17.3" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.3.tgz";
        sha512 = "SYU4z1dL0PyIMd4Vj8YOqFvHu7Hz/enbWtpfnVbJHU4Nd1YNYx8u0ennumc6h48GQNeOLxmwySmnADouT/AuZA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "webidl-conversions-3.0.1" = {
      name = "webidl-conversions";
      packageName = "webidl-conversions";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/webidl-conversions/-/webidl-conversions-3.0.1.tgz";
        sha512 = "2JAn3z8AR6rjK8Sm8orRC0h/bcl/DqL7tRPdGZ4I1CjdF+EaMLmYxBHyXuKL849eucPFhvBoxMsflfOb8kxaeQ==";
      };
    };
    "whatwg-url-5.0.0" = {
      name = "whatwg-url";
      packageName = "whatwg-url";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/whatwg-url/-/whatwg-url-5.0.0.tgz";
        sha512 = "saE57nupxk6v3HY35+jzBwYa0rKSy0XR8JSxZPwgLr7ys0IBzhGviA1/TUGJLmSVqs8pb9AnvICXEuOHLprYTw==";
      };
    };
    "wrappy-1.0.2" = {
      name = "wrappy";
      packageName = "wrappy";
      version = "1.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/wrappy/-/wrappy-1.0.2.tgz";
        sha512 = "l4Sp/DRseor9wL6EvV2+TuQn63dMkPjZ/sp9XkghTEbV9KlPS1xUsZ3u7/IQO4wxtcFB4bgpQPRcR3QCvezPcQ==";
      };
    };
    "yaml-2.7.1" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.7.1.tgz";
        sha512 = "10ULxpnOCQXxJvBgxsn9ptjq6uviG/htZKk9veJGhlqn3w/DxQ631zFF+nlQXLwmImeS5amR2dl2U8sg6U9jsQ==";
      };
    };
  };
in
{
  gh-actions-language-server = nodeEnv.buildNodePackage {
    name = "gh-actions-language-server";
    packageName = "gh-actions-language-server";
    version = "0.0.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/gh-actions-language-server/-/gh-actions-language-server-0.0.3.tgz";
      sha512 = "T2ph7OoS0tnpWsxpvdiC5k9rrv5t7BMwZRJANrk4gZzvTZ1/rY1kpJQjVaiYeTrlj2fDgQh5fMwPqkxNaKIGdw==";
    };
    dependencies = [
      sources."@actions/expressions-0.3.15"
      sources."@actions/languageserver-0.3.15"
      sources."@actions/languageservice-0.3.15"
      sources."@actions/workflow-parser-0.3.15"
      sources."@octokit/auth-token-3.0.4"
      sources."@octokit/core-4.2.4"
      sources."@octokit/endpoint-7.0.6"
      sources."@octokit/graphql-5.0.6"
      sources."@octokit/openapi-types-18.1.1"
      sources."@octokit/plugin-paginate-rest-6.1.2"
      sources."@octokit/plugin-request-log-1.0.4"
      (sources."@octokit/plugin-rest-endpoint-methods-7.2.3" // {
        dependencies = [
          sources."@octokit/types-10.0.0"
        ];
      })
      sources."@octokit/request-6.2.8"
      sources."@octokit/request-error-3.0.3"
      sources."@octokit/rest-19.0.13"
      sources."@octokit/tsconfig-1.0.2"
      sources."@octokit/types-9.3.2"
      sources."before-after-hook-2.2.3"
      sources."cronstrue-2.57.0"
      sources."deprecation-2.3.1"
      sources."encoding-0.1.13"
      sources."iconv-lite-0.6.3"
      sources."is-plain-object-5.0.0"
      sources."node-fetch-2.7.0"
      sources."once-1.4.0"
      sources."safer-buffer-2.1.2"
      sources."tr46-0.0.3"
      sources."typescript-5.8.2"
      sources."universal-user-agent-6.0.1"
      sources."vscode-jsonrpc-8.1.0"
      sources."vscode-languageserver-8.1.0"
      (sources."vscode-languageserver-protocol-3.17.3" // {
        dependencies = [
          sources."vscode-languageserver-types-3.17.3"
        ];
      })
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-uri-3.1.0"
      sources."webidl-conversions-3.0.1"
      sources."whatwg-url-5.0.0"
      sources."wrappy-1.0.2"
      sources."yaml-2.7.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "**GitHub Actions Language Server**";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@anthropic-ai/claude-code" = nodeEnv.buildNodePackage {
    name = "_at_anthropic-ai_slash_claude-code";
    packageName = "@anthropic-ai/claude-code";
    version = "0.2.60";
    src = fetchurl {
      url = "https://registry.npmjs.org/@anthropic-ai/claude-code/-/claude-code-0.2.60.tgz";
      sha512 = "axaARQIqPWdDfcS+ZyHNomIRmfkPr6AL51Tb+BtvtWrs0mP1kHPVoLP/o290U7X8XaYlP5DIpWkxjag4ES5+Dg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Use Claude, Anthropic's AI assistant, right from your terminal. Claude can understand your codebase, edit files, run terminal commands, and handle entire workflows for you.";
      homepage = "https://github.com/anthropics/claude-code";
      license = "SEE LICENSE IN README.md";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
